"""create base_models and trainer_registry tables

Revision ID: 74b2529fd35d
Revises: 4803da49de22
Create Date: 2026-07-02 22:29:23.371535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.types


revision: str = '74b2529fd35d'
down_revision: Union[str, None] = '4803da49de22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_models',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('family', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_models_name'), 'base_models', ['name'], unique=True)
    op.create_table('trainer_registry',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('trainer_name', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('base_model_family', sa.String(length=64), nullable=False),
    sa.Column('entrypoint', sa.String(length=255), nullable=False),
    sa.Column('docker_image', sa.String(length=255), nullable=True),
    sa.Column('supported_resume', sa.Boolean(), nullable=False),
    sa.Column('supported_export_formats', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainer_registry_trainer_name'), 'trainer_registry', ['trainer_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainer_registry_trainer_name'), table_name='trainer_registry')
    op.drop_table('trainer_registry')
    op.drop_index(op.f('ix_base_models_name'), table_name='base_models')
    op.drop_table('base_models')
    # ### end Alembic commands ###
